version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /syno/docker/jellyfin:/config
      - /syno/media/Video:/data/tvshows
      - /syno/media/Music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped
