version: "3"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "4G"
      VERSION: "1.21.1"
      SEED: "-2243392742249635263"
      UID: 1000
      GID: 1000
    volumes:
      - /syno/docker/minecraft:/data
